from employees import Employee

# THIS PROGRAM MANAGES JACK DUKE AUTOSALES INC. EMPLOYESS, INVENTORY AND SALES
# AUTHOR: JOHNFISHER UCHEM
# PROJECT NAME: JACK DUKE AUTOSALES INC APP. MANAGER
# SOFTWARE PROJECT TYPE: DUMMY PROJECT
# CLIENT: JACK DUKE AUTOSALES INC.

# Launch this application project
Employee.launch_app()











